# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 06:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temple', '0006_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
