# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='class_name',
            new_name='class_level',
        ),
        # migrations.AddField(
        #     model_name='student',
        #     name='created',
            # field=models.DateTimeField(auto_now_add=True, default="123"),
            # preserve_default=False,
        # ),
    ]
"""
(datetime.datetime(2016, 11, 1, 7, 15, 12, 655838, tzinfo=utc)
"""
