# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 05:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20171209_0514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='class_level',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
