# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20171209_0518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Class')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Profile')),
            ],
        ),
    ]
